'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MfgControl.AdvancedHMI.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _200w() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("200w", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _308653_200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("308653-200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _7784602() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("7784602", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AdvancedHMILogoBR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AdvancedHMILogoBR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlarmAudibleError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlarmAudibleError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlarmAudibleOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlarmAudibleOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlarmAudibleOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlarmAudibleOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlarmFalconError() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlarmFalconError", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlarmFalconOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlarmFalconOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property AlarmFalconOn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AlarmFalconOn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property analogcard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("analogcard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property analogcard2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("analogcard2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [A0]
        '''title=City Water Pre-Filter Pressure
        '''ValueADD=F30:0
        '''HighlightADD=N14:30/0
        '''ValueUNIT=PSI
        '''TodaysMinADD=
        '''TodaysMaxADD=
        '''SetpointMode=
        '''SP=
        '''TOL=
        '''MIN=
        '''MAX=
        '''[A1]
        '''title=
        '''ValueADD=
        '''HighlightADD=
        '''ValueUNIT=
        '''TodaysMinADD=
        '''TodaysMaxADD=
        '''SetpointMode=
        '''SP=
        '''TOL=
        '''MIN=
        '''MAX=
        '''[A2]
        '''title=
        '''ValueADD=
        '''HighlightADD=
        '''ValueUNIT=
        '''TodaysMinADD=
        '''TodaysMaxADD=
        '''SetpointMode=
        '''SP=
        '''TOL=
        '''MIN=
        '''MAX=
        '''[A3]
        '''title=
        '''ValueADD=
        '''HighlightADD=
        '''ValueUNIT=
        '''TodaysMinADD=
        '''TodaysMaxADD=
        '''SetpointMode=
        '''SP=
        '''TOL= [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AnalogSettings() As String
            Get
                Return ResourceManager.GetString("AnalogSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ATLAS_Comp3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ATLAS_Comp3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BADBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BADBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BADBG_BAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BADBG_BAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BadPumpBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BadPumpBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property bell_alarm() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bell-alarm", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtonG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtonOFF() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonOFF", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtonR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ButtonY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ButtonY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property condensate_pit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("condensate_pit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CP_COMPRESSOR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CP_COMPRESSOR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CP_COMPRESSOR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CP_COMPRESSOR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cpucard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cpucard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cpucard1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cpucard1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DeairatorTank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DeairatorTank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DewPointSensor() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DewPointSensor", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DisplayPanel3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DisplayPanel3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DownFlow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DownFlow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dryer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dryer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dryer2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dryer2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ezgif_4_68b6536f13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ezgif-4-68b6536f13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Fire() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fire", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Flame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeBar_Black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeBar_Black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeBar_YGR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeBar_YGR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeBar2_Black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeBar2_Black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeBar2_GR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeBar2_GR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeBar2_GYR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeBar2_GYR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GaugeBar2_YGR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GaugeBar2_YGR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GOODBG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GOODBG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GOODBG_BAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GOODBG_BAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GoodPumpBody() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GoodPumpBody", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property inputcard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inputcard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LargeBoiler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LargeBoiler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LeftFlow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LeftFlow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_CoilBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_CoilBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_CoilEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_CoilEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_CoilGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_CoilGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_FireHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_FireHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_FireLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_FireLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_FireNone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_FireNone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_WaterGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_WaterGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_WaterHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_WaterHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_WaterLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_WaterLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LG_WaterNone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LG_WaterNone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogFileBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogFileBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LogFileGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LogFileGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MainDispLongGRADt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MainDispLongGRADt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outputcard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outputcard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PlateExchanger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PlateExchanger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PSUcard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PSUcard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RightFlow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RightFlow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property riocard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("riocard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [SYSTEM]
        '''PLCIP=10.20.50.150
        '''TopMost=True
        '''EN_DataLog=True
        '''Inactivity_Timeout=1
        '''UserLogin_Timeout=5
        '''[ALARM]
        '''LB_EN=True
        '''LB_Freq=500
        '''LB_Pulse=3
        '''LB_Pause=3000
        '''SB_EN=True
        '''SB_Freq=80
        '''SB_Pulse=3
        '''SB_Pause=10000
        '''AL_Sil_Timeout=12800
        '''AL_ByP_Timeout=12800
        '''[DATALOG]
        '''DataLOG_Loc=C:\FacilityMonitorLogs\DataLogs
        '''AlarmLOG_Loc=C:\FacilityMonitorLogs\AlarmLogs
        '''ChangeLOG_Loc=C:\FacilityMonitorLogs\ChangeLogs
        '''AdminLOG_Loc=C:\FacilityMonitorLogs\AdminLogs
        '''EquipLOG_Loc=C:\FacilityMonitorLogs\EquStatLogs
        '''Min [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property settings() As String
            Get
                Return ResourceManager.GetString("settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_CoilBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_CoilBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_CoilEmpty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_CoilEmpty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_CoilGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_CoilGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_FireHigh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_FireHigh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_FireLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_FireLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_FireNone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_FireNone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_WateHighr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_WateHighr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_WaterGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_WaterGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_WaterLow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_WaterLow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SM_WaterNone() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SM_WaterNone", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SmallBoiler() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallBoiler", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Softener1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Softener1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAirBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAirBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusAirGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusAirGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusElecBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusElecBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusElecGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusElecGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusPLCBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusPLCBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusPLCGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusPLCGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusSteamBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusSteamBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusSteamGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusSteamGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusWaterBad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusWaterBad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property StatusWaterGood() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StatusWaterGood", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_00() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_00", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property strangeindicator_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("strangeindicator_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SystemAirTanks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SystemAirTanks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TEV_Ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TEV_Ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrilliumLogo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrilliumLogo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TubeShellExchanger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TubeShellExchanger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UPFlow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UPFlow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UpFlow2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UpFlow2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Water_Filter_Single() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Water_Filter_Single", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
